// import style from "./Images.module.css";

export const imageData = [
  {
    id: 1,
    src: "https://i.pinimg.com/originals/98/bb/5d/98bb5d3a61703af676724ae8817ab2f1.jpg",
    alt: "Descripción de la imagen 1",
    title: "Parque de los Lençóis Maranhenses",
    continent: "América del Sur",
    pais: "Brasil",
    region: "Maranhão",
    clima: "Tropical (con estación húmeda y estación seca)",
    deporte: "Sandboarding y paseos en buggy",
  },
  {
    id: 2,
    src: "https://upload.wikimedia.org/wikipedia/commons/d/db/CA%C3%91O_CRISTALES%2C_EL_R%C3%8DO_DE_COLORES.jpg",
    alt: "Descripción de la imagen 2",
    title: "Caño Cristales",
    continent: "América del Sur",
    pais: "Colombia",
    region: "Meta",
    clima: "Tropical",
    deporte: "Senderismo y observación de los vibrantes colores del río",
  },
  {
    id: 3,
    src: "https://triptins.com/wp-content/uploads/2016/03/Java-Waterfall.jpeg",
    alt: "Descripción de la imagen 1",
    title: "Tumpak Sewu",
    continent: "Asia",
    pais: "Indonesia",
    region: "Java Oriental",
    clima: "Tropical",
    deporte: "Senderismo y cascading (descenso de cascadas)",
  },
  {
    id: 4,
    src: "https://p4.wallpaperbetter.com/wallpaper/145/258/363/val-di-funes-dolomites-italy-wallpaper-preview.jpg",
    alt: "Descripción de la imagen 2",
    title: "Dolomitas, Italia",
    continent: "Europa",
    pais: "Italia",
    region: "Región del Véneto, Trentino-Alto Adigio, Friuli-Venecia Julia",
    clima: "Templado (Alpino)",
    deporte: "Senderismo, escalada y esquí.",
  },
  {
    id: 5,
    src: "https://media.istockphoto.com/id/155384430/es/foto/argentina-iguaz%C3%BA-cascadas-garganta-del-diablo-con-rainbow.jpg?s=612x612&w=0&k=20&c=nkZKTmoyGrwbW22YTXwCGfRnpQDccPH79FeS_q3UM-I=",
    alt: "Descripción de la imagen 1",
    title: "Cataratas de Iguazu, Argentina",
    continent: "América del Sur",
    pais: "Argentina y Brasil (las cataratas cruzan la frontera entre ambos países)",
    region: "Provincia de Misiones en Argentina y estado de Paraná en Brasil",
    clima: "Subtropical",
    deporte: "Paseos en bote y senderismo.",
  },
  {
    id: 6,
    src: "https://p4.wallpaperbetter.com/wallpaper/960/576/933/waterfalls-angel-falls-cliff-mountain-wallpaper-preview.jpg",
    alt: "Descripción de la imagen 2",
    title: "Salto Ángel, Venezuela",
    continent: "América del Sur",
    pais: "Venezuela",
    region: "Canaima",
    clima: "Tropical",
    deporte: "Trekking y avistamiento de aves",
  },
  {
    id: 7,
    src: "https://w0.peakpx.com/wallpaper/933/693/HD-wallpaper-norway-mountains-lysefjord-cliffs-preikestolen.jpg",
    alt: "Descripción de la imagen 1",
    title: "Lysefjord, Noruega",
    continent: "Europa",
    pais: "Noruega",
    region: "Vestlandet",
    clima: "Templado (clima oceánico)",
    deporte: "Senderismo y escalada",
  },
  {
    id: 8,
    src: "https://p4.wallpaperbetter.com/wallpaper/536/878/532/man-made-path-forest-green-wallpaper-preview.jpg",
    alt: "Descripción de la imagen 2",
    title: "Parque Nac. de las Secuoyas, EE.UU. ",
    continent: "América del Norte",
    pais: "Estados Unidos (California)",
    region: "Sierra Nevada",
    clima: "Variado, desde mediterráneo hasta alpino",
    deporte: "Senderismo y exploración de bosques",
  },
  {
    id: 9,
    src: "https://w0.peakpx.com/wallpaper/705/554/HD-wallpaper-australia-the-great-barrier-reef-barrier-australia-aqua-blue-sea-view-from-the-top-reef-water-vara-summer-skin.jpg",
    alt: "Descripción de la imagen 1",
    title: "Gran Barrera de Coral, Australia",
    continent: "Oceanía",
    pais: "Australia",
    region: "Queensland",
    clima: "Tropical (varía en diferentes partes de la barrera)",
    deporte: "Buceo y snorkel",
  },
  {
    id: 10,
    src: "https://store-images.s-microsoft.com/image/apps.40340.13844868329507759.07372d86-a484-4a8f-a924-abf609635a3e.9518ce59-c3a3-4d62-9a12-46972782bbc9",
    alt: "Descripción de la imagen 2",
    title: "Lago Baikal, Rusia",
    continent: "Asia",
    pais: "Rusia",
    region: "Siberia",
    clima: "Subártico",
    deporte: "Patinaje sobre hielo (invierno), senderismo y turismo",
  },
  {
    id: 11,
    src: "https://www.wallpaperflare.com/static/862/544/850/wadi-rum-jordan-landscape-photo-wallpaper.jpg",
    alt: "Descripción de la imagen 2",
    title: "Wadi Rum, Jordania",
    continent: "Asia",
    pais: "Jordania",
    region: "Aqaba",
    clima: "Desértico",
    deporte: "Senderismo y recorridos en vehículos todoterreno por el desierto",
  },
  {
    id: 12,
    src: "https://i0.wp.com/armandotuviaje.blog/wp-content/uploads/2017/03/beautiful-halong-bay.jpeg?fit=1600%2C958&ssl=1",
    alt: "Descripción de la imagen 2",
    title: "Bahía de Ha Long, Vietnam",
    continent: "Asia",
    pais: "Vietnam",
    region: "Provincia de Cao Bang",
    clima: "Tropical",
    deporte: "Turismo y observación de cascadas",
  },
  {
    id: 13,
    src: "https://p4.wallpaperbetter.com/wallpaper/798/865/266/cliff-clouds-nature-sunset-wallpaper-preview.jpg",
    alt: "Descripción de la imagen 1",
    title: "Islas Faroe, Islas Faroe",
    continent: "Europa",
    pais: "Islas Feroe (territorio autónomo de Dinamarca)",
    region: "Atlántico Norte",
    clima: "Oceánico subpolar",
    deporte: " Senderismo, observación de aves y paisajes impresionantes",
  },
  {
    id: 14,
    src: "https://wallpaperaccess.com/full/1408398.jpg",
    alt: "Descripción de la imagen 2",
    title: "Capadocia, Tuquía",
    continent: "Asia",
    pais: "Turquía",
    region: "Anatolia Central",
    clima: "Continental",
    deporte: "Vuelos en globo aerostático y senderismo",
  },
  {
    id: 15,
    src: "https://i.pinimg.com/originals/03/55/66/0355667b998b629d6ee75d4bfceb51af.jpg",
    alt: "Descripción de la imagen 1",
    title: "Cenotes de México, Mexico",
    continent: "América del Norte",
    pais: "México",
    region: "Chiapas",
    clima: "Tropical",
    deporte: "Recorridos en bote y observación de aves",
  },
  {
    id: 16,
    src: "https://1.bp.blogspot.com/-cJwAgjXR7CA/WnzR36GUJDI/AAAAAAAAF2k/iXtgEcM43norB0DbTkUgsHY1FT_btF7kgCPcBGAYYCw/s1600/post114.jpg",
    alt: "Descripción de la imagen 2",
    title: "Desierto de Namib, Namibia",
    continent: "África",
    pais: "Namibia",
    region: "Namib",
    clima: "Desértico",
    deporte: "Exploración de dunas, observación de vida silvestre y fotografía",
  },
  {
    id: 17,
    src: "https://wallpapers.com/images/hd/serengeti-national-park-lioness-sitting-a4fhql5knux0szut.jpg",
    alt: "Descripción de la imagen 2",
    title: "Parque Nac. Serengueti, Tanzania",
    continent: "África",
    pais: "Tanzania",
    region: "Región de Mara y Simiyu",
    clima: "Tropical",
    deporte: "Safaris y observación de vida silvestre",
  },
  {
    id: 18,
    src: "https://w0.peakpx.com/wallpaper/644/357/HD-wallpaper-etretat-normandy-france-cliff-sky-sea-landscape.jpg",
    alt: "Descripción de la imagen 1",
    title: "Acantilados de Étretat, Francia",
    continent: "Europa",
    pais: "Francia",
    region: "Normandía",
    clima: "Oceánico",
    deporte: "Senderismo y observación de acantilados y el mar",
  },
  {
    id: 19,
    src: "https://w0.peakpx.com/wallpaper/686/710/HD-wallpaper-lake-lovatnet-morning-mountains-waterfalls-norway.jpg",
    alt: "Descripción de la imagen 2",
    title: "Lago Novatnet, Suecia",
    continent: "Europa",
    pais: "Suecia",
    region: "Lappland",
    clima: "Subártico",
    deporte: "Pesca, canotaje y observación de la aurora boreal",
  },
  {
    id: 20,
    src: "https://img.peapix.com/eb44fcae8ffd4883ba4b413adca5e89b.jpg?attachment&modal",
    alt: "Descripción de la imagen 2",
    title: "Avenida de los Baobabs, Madagascar",
    continent: "África",
    pais: "Madagascar",
    region: "Región de Menabe",
    clima: "Tropical",
    deporte: "Observación de los icónicos baobabs y la naturaleza de la región",
  },
];
